### ISSUE TITLE
Specialization-ebuild getting renamed

### ISSUE THREAD

**Issue by Doeme** [IBT-FMI/gebuilder#39]
The ebuild from the .gentoo will get renamed (to `specialization-99999.ebuild`), resulting in `${P}` being unusable inside it.

We should probably just copy over the .gentoo structure already provided, and maybe add a /etc/portage/sets for the specialization.

**Comment by TheChymera** [comment]
I'm not sure what you mean exactly. In any case:

* Defining a package set for the dependencies of the target ebuild (if this is what you meant) is a really bad idea, not least of all, because package sets don't offer as many features as `DEPEND`. They're basically designed for operator→software interaction specifically, and not software→software interaction.
* Defining a package set containing the package and only the package, would be a nice way to alias the name, so that we can `emerge @specialization`, without having to obfuscate the name of the ebuild.

Also, didn't we settle for `packagename-99999.ebuild` --- five nines. We don't want this accidentally superseded by live versions from overlays.

**Comment by Doeme** [comment]
>  * Defining a package set containing the package and only the package, would be a nice way to alias the name, so that we can `emerge @specialization`, without having to obfuscate the name of the ebuild.

This is exactly what I was proposing.
It just remains to determine whether we can also install all dependencies for a set with `emerge -o`
> 
> Also, didn't we settle for `packagename-99999.ebuild` --- five nines. We don't want this accidentally superseded by live versions from overlays.

Indeed. Fixed it above.
